# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd

df = pd.read_csv("salary_data.csv")

X = df["YearsExperience"]
Y= df["Salary"]

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42)

X_rain_reshaped = X_train.values.reshape(-1, 1)

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_rain_reshaped, Y_train)

X_test_reshaped = X_test.values.reshape(-1, 1)
Y_pred = model.predict(X_test_reshaped)

from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(Y_test, Y_pred)
r2 = r2_score(Y_test, Y_pred)

print(f"Mean Square Error: {mse:.2f}")
print(f"R^2 Score: {r2:.2f}")

import matplotlib.pyplot as plt

plt.figure(figsize = (4, 3))
plt.scatter(X, Y, color = "gray", label = "Actual Data")
plt.plot(X_test, Y_pred, color = "black", linewidth = 2, label = "Regression Line")
plt.title("Years of Experince vs salary")
plt.ylabel("YOE")
plt.xlabel("Salary")
plt.grid(True)
plt.legend()
plt.show()